version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./redis/d–∞ta:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=${REDIS_DATABASES:-16}